### ISSUE TITLE
Convert "NFC writing guide" to Markdown

### ISSUE THREAD

**Issue by kg4zow** [AmiiboDB/Amiibo#1]
Is it possible to convert this document to Markdown, so that people can read it in the Github web interface rather than having to download it and possibly convert it to an open format before we can read it?

Thanks.

**Comment by AmiiboDB** [comment]
> Is it possible to convert this document to Markdown, so that people can read it in the Github web interface rather than having to download it and possibly convert it to an open format before we can read it?
> 
> Thanks.

Yeah I can convert it to a markup file if that helps.
